// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt6plaiBClkdn9AdF2nWDTjwf6gPmnK5M',
    appId: '1:783540571618:web:50dfacba8cbab3c4e9fdbb',
    messagingSenderId: '783540571618',
    projectId: 'music-app-01-tutorial',
    authDomain: 'music-app-01-tutorial.firebaseapp.com',
    storageBucket: 'music-app-01-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7vvTiCT0AKIOmKsPfaJEbfjM75wtY5jw',
    appId: '1:783540571618:android:1c91c1abe91a5e88e9fdbb',
    messagingSenderId: '783540571618',
    projectId: 'music-app-01-tutorial',
    storageBucket: 'music-app-01-tutorial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbbEmuJqo6G9G5kRo88LWZj-cFfFFBJaY',
    appId: '1:783540571618:ios:286feac030c8feede9fdbb',
    messagingSenderId: '783540571618',
    projectId: 'music-app-01-tutorial',
    storageBucket: 'music-app-01-tutorial.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbbEmuJqo6G9G5kRo88LWZj-cFfFFBJaY',
    appId: '1:783540571618:ios:286feac030c8feede9fdbb',
    messagingSenderId: '783540571618',
    projectId: 'music-app-01-tutorial',
    storageBucket: 'music-app-01-tutorial.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt6plaiBClkdn9AdF2nWDTjwf6gPmnK5M',
    appId: '1:783540571618:web:fe44b5b88472a69de9fdbb',
    messagingSenderId: '783540571618',
    projectId: 'music-app-01-tutorial',
    authDomain: 'music-app-01-tutorial.firebaseapp.com',
    storageBucket: 'music-app-01-tutorial.firebasestorage.app',
  );
}
